### ISSUE TITLE
Closing myPlan by pressing back

### ISSUE THREAD

**Issue by daniel-lerch** [jrheiner/myplan#1]
When you attempt to close _myPlan_ using the android navigation button, you will see the main activity several times, the login activity once and after this the app will close.

Once logged in, the user should not be able to get back to the login activity except by clicking Logout in the drop down menu.

Pressing the back button should navigate the user to the previous activity which should never be the same. At the moment it is possible to navigate back to activities with the previously selected color theme.

**Comment by jrheiner** [comment]
Thank you for your report. This is not intended.
