### ISSUE TITLE
Redesign timetable concept

### ISSUE THREAD

**Issue by daniel-lerch** [jrheiner/myplan#17]
I would like to discuss a different approach for setting up a custom timetable.

1. Timetables have no relevance from 5th to 9th grade with class system. The option could be given in the settings activity but not on the main activity.
2. Only a few people with course system will configure a timetable as it is complicated and many of them want to know about lessons of their friends not taking place.
3. Your timetable does not change often. The designer should be moved in the settings section. But it should also be shown on first startup when you select a grade from 10 to 12.
4. It would be great to toggle timetable filtering with just one touch. The currently existing button could be used to switch timetable filtering on and off.
5. As you usually have one teacher for one subject it would be faster to first select a subject with the matching teacher and afterwards marking all lessons in an empty timetable of this subject. It might be a little bit confusing as we are used to writes tables column by column but it would be much faster this way especially on a smartphone.

**Comment by jrheiner** [comment]
- [ ] Timetables have no relevance from 5th to 9th grade with class system. The option could be given in the settings activity but not on the main activity.

- [ ] Only a few people with course system will configure a timetable as it is complicated and many of them want to know about lessons of their friends not taking place.

- [ ] Your timetable does not change often. The designer should be moved in the settings section. But it should also be shown on first startup when you select a grade from 10 to 12.

- [ ] It would be great to toggle timetable filtering with just one touch. The currently existing button could be used to switch timetable filtering on and off.

- [ ] As you usually have one teacher for one subject it would be faster to first select a subject with the matching teacher and afterwards marking all lessons in an empty timetable of this subject. It might be a little bit confusing as we are used to writes tables column by column but it would be much faster this way especially on a smartphone.

**Comment by daniel-lerch** [comment]
A really good timetable implementation is too much work for such a simple project like myPlan. I would recommend to remove all timetable features in the `tt_redesign` Branch to keep all other changes. Furthermore the implementation would stay in the commit history and could be restored in the future.

**Comment by jrheiner** [comment]
I agree, as of now the timetable filter has been removed. Additionally to the git history I will leave the branch `tt_redesign` open for future reference.
