### ISSUE TITLE
Remove notifications on reload

### ISSUE THREAD

**Issue by daniel-lerch** [jrheiner/myplan#19]
Since #13 has been fixed, most notifications are removed correctly. However there is still one scenario where notifications are not dismissed automatically.  
This happens when the device goes in sleep mode while having myPlan as foreground application. Once the user wakes up the device again, myPlan reloads the plan but does not dismiss a notification which was created by the service while the device was sleeping.

**Comment by jrheiner** [comment]
This scenario was indeed not taken into account. Thank you for you report!
