### ISSUE TITLE
Show general messages

### ISSUE THREAD

**Issue by daniel-lerch** [jrheiner/myplan#4]
Some representations or canceled hours are not shown for each class but in a section called _Nachrichten zum Tag_. Especially the row _Unterrichtsfrei_ only appears in some weeks but is very important for all pupils. This information has to shown somehow to the user.

**Comment by jrheiner** [comment]
*Added in bf7b30012891c671e9dd254b31be762e160114c0*
App now shows the *Unterrichtsfrei* message. If there is more information that affects all students feel free to notify me.
