### ISSUE TITLE
Notification Icon for dark system designs

### ISSUE THREAD

**Issue by daniel-lerch** [jrheiner/myplan#5]
Many Android distributions use a dark notification bar design. The current notification icon does not fit these designs. As all other icons do, the myPlan notification icon should change its color like text automatically changes from black to white.

**Comment by jrheiner** [comment]
Thank you for your report. However in my personal perception the notification icon is visible just fine even when using the dark theme.
I tested using android api level 22 and 27.

[results](https://imgur.com/a/vWhJVbM)
